name: Ansible CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ansible and sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible sshpass

    - name: Add SSH password and run Ansible playbook
      run: |
        # Disable host key checking to avoid errors with unknown hosts
        echo "Host *" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
        
        # Use sshpass to provide the SSH password for Ansible
        sshpass -p "${{ secrets.ANSIBLE_SSH_PASS }}" ansible-playbook -i inventory.ini playbooks/install-node.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'False'
